### ISSUE TITLE
I can't get the mangarr backend container to work

### ISSUE THREAD

**Issue by xavimaa** [tnrd-org/Mangarr#2]
Hello,

I tried to install mangarr but the mangarr backed container doesn't work.
I'm attaching my docker compose file and logs, can you help me?

I'm not a developer but I'd like to install it and use it to give you feedback 😊

[docker-compose.txt](https://github.com/tnrd-org/Mangarr/files/14013371/docker-compose.txt)
[_mangarr.backend_logs.txt](https://github.com/tnrd-org/Mangarr/files/14013373/_mangarr.backend_logs.txt)

**Comment by Thundernerd** [comment]
It seems like it is unable to find the mongodb container which is kind of odd as it should be able to find it through the host name.

Are you using a tool like portainer? It isn't a great solution but you could try to find the `mangarr.db` container's ip address and fill that in as the value for the `MONGO__HOST` environment variable.

Another thing worth noting is that I'm currently doing a pretty hefty rewrite which will combine the frontend and backend into one, but of course feel free to try out the current version and leave feedback, that is very much appreciated :)

**Comment by xavimaa** [comment]
Thanks for your reply.
I'll wait for the project rewrite to install it because I really believe in the project.
I suggest you separate the extensions on a repository external to the application to avoid being in a situation like the Tachiyomi app...

I'll be happy to give you feedback once mangarr is installed :)

**Comment by Thundernerd** [comment]
Thanks for the suggestion! I am indeed planning on separating it to avoid exactly that :)

**Comment by Thundernerd** [comment]
@xavimaa I've published the combined version and have updated the example docker-compose.yml in the root of the repo. Feel free to try it!

If you run into any issues you can poke me here. And if everything is working as expected then you can close the issue :)

**Comment by xavimaa** [comment]
Hi,

Thanks for your return. 
I just tried setting the IP address to the MONGO__HOST environment variable but I got errors.
![image](https://github.com/tnrd-org/Mangarr/assets/82511742/0cc85918-85db-4526-8dc3-bb9eb29a71ef)

I actually think it comes from my configuration with Portainer. I will try to resolve this problem this weekend :)
[_mangarr.stack_logs.txt](https://github.com/tnrd-org/Mangarr/files/14089822/_mangarr.stack_logs.txt)

**Comment by Thundernerd** [comment]
You should remove the `http://` from `MONGO__HOST`. The actual connection string for connecting to the db will be turned into `mongodb://username:password@host:port`, so if your host starts with `http://` then it'll be incorrect!

**Comment by xavimaa** [comment]
I've just tried it but I'm getting the same errors :/

**Comment by Thundernerd** [comment]
Can you show your config and logs?

**Comment by xavimaa** [comment]
Hi! Thanks again for your help!
I think I know where the problem comes from. 
I have this error with mongo: **`WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!`**

The Pentium J5040 cpu on my not-so-old NAS doesn't seem to support AVX instructions.

If you have a solution I'd love to hear from you :)
[_mangarr.db_logs20240130.txt](https://github.com/tnrd-org/Mangarr/files/14103968/_mangarr.db_logs20240130.txt)
[_mangarr.stack_logs20240130.txt](https://github.com/tnrd-org/Mangarr/files/14103969/_mangarr.stack_logs20240130.txt)
[docker-compose.txt](https://github.com/tnrd-org/Mangarr/files/14103970/docker-compose.txt)

**Comment by Thundernerd** [comment]
Hm. I can't guarantee that it'll work, but you could try changing the image tag from the mongodb container in your docker-compose file 

from
```
image: mongo
```
to
```
image: mongo:4
```

**Comment by xavimaa** [comment]
I've just tried it, there are no more errors with mango in version 4 but I still get errors with mangarr.

Is it possible to offer an alternative database system in the future?
[_mangarr.stack_logs20240131.txt](https://github.com/tnrd-org/Mangarr/files/14117273/_mangarr.stack_logs20240131.txt)

**Comment by Thundernerd** [comment]
> Is it possible to offer an alternative database system in the future?

It isn't to plan to support that, for now at least.

> I've just tried it, there are no more errors with mango in version 4 but I still get errors with mangarr.

I suspect that the ip address you have filled in isn't correct, one thing I would recommend based on your last docker-compose, is replace the ip address for `MONGO__HOST` to `mangarr.db`

If you run into the same problem with the cache then you should change the value for `REDIS__HOST` to `mangarr.cache`
