### ISSUE TITLE
Support configuring base url

### ISSUE THREAD

**Issue by nickexyz** [tnrd-org/Mangarr#4]
Thanks for creating an awesome project, really looking forward to how it will develop!

No rush, but at some point it would be awesome if we could configure the base url for the application.
I'm planning to run it behind a reverse proxy at https://example.com/mangarr

I couldn't find anything about it, but maybe it's possible already?

**Comment by Thundernerd** [comment]
That currently isn't possible, but it is definitely a good thing to add. I'll add it on the to-do list :)

**Comment by nickexyz** [comment]
Perfect, cheers! :)
