### ISSUE TITLE
Only monitor new chapters doesn't do anything

### ISSUE THREAD

**Issue by Rudranil-Sarkar** [tnrd-org/Mangarr#6]
The title kinda explains itself. The checkbox Only monitor new chapters has no effect. 

I love what you are doing. I was hoping to contribute but I'm know nothing abot C#.

**Comment by Thundernerd** [comment]
Apologies for the late reply, github notifications are horrible.

The intended functionality for only monitor new chapters is that it looks at the chapters that exist at the moment that you add the manga but doesn't download them, only ones that are added to the list after that. Are you saying that that isn't working?

**Comment by Rudranil-Sarkar** [comment]
Yes basically even if I check that box it still downloads all of the chapters.

**Comment by Thundernerd** [comment]
Thanks for the info. I'll have a look asap.

**Comment by Thundernerd** [comment]
Was able to reproduce the issue and luckily it was a relatively easy fix!

A new image has been built and pushed to docker hub so if you pull the latest version it should now be working for you.
