### ISSUE TITLE
keeps searching for items, and then a error occured, applications needs to be reloaded

### ISSUE THREAD

**Issue by undeadalien1** [tnrd-org/Mangarr#8]
hi, 

ill start by saying im no linux pro, nor docker pro,  
i have a alphine installation with docker, and used portainer to use your docker-compose and only changed the passwords.
when i select several sources and search for a manga(i searched for "the gamer"  with quotes, the name of the manga pops up,  i click add,
with several sources i get "An error has occurred. This application may no longer respond until reloaded. [Reload]" right away,
with 1 sources it sometimes happesn right away, sometimes it takes abit.   ive had the screen open for over an hour and still it doesnt show anything.

ive attached all 4 of the logs,
any tips?
[_mangarr.stack_logs.txt](https://github.com/tnrd-org/Mangarr/files/14923365/_mangarr.stack_logs.txt)
[_mangarr.db_logs.txt](https://github.com/tnrd-org/Mangarr/files/14923367/_mangarr.db_logs.txt)
[_mangarr.flaresolverr_logs.txt](https://github.com/tnrd-org/Mangarr/files/14923368/_mangarr.flaresolverr_logs.txt)
[_mangarr.cache_logs.txt](https://github.com/tnrd-org/Mangarr/files/14923369/_mangarr.cache_logs.txt)

**Comment by Thundernerd** [comment]
Hey there,

No worries that you're not a pro in either of those, you've provided the logs which was all I needed!

It seems that when trying to add a manga it fails to find a root directory where it can put it in and therefore breaks unexpectedly. Ideally this would be handled appropriately but in the mean time until that is added you can fix this issue by manually adding a root folder.

You can add a root folder by going through the following steps (added an image below to make it clear what I mean)
1. Click on the Settings menu item
2. Type in the path to where you want your mangas stored (in the image below you can see that mine go into /mnt/comics)
3. Click the add button

![image](https://github.com/tnrd-org/Mangarr/assets/5531467/aa79cf3d-a780-425b-81ca-be1c6d8bb6e4)

Once you've done this you should be able to properly download mangas!

**Comment by undeadalien1** [comment]
alraighty,  then ill first have to see how i can mount my nas on this thing;)
ill let u know if it worked out

**Comment by Thundernerd** [comment]
Sure thing! Let me know if you run into any other issues :)

**Comment by undeadalien1** [comment]
welllll,  i did get 1 step further,   now i could select a source,  then select the location aaaand crash..
in the alphine LCX (kind of container from proxmox) i have docker installed, and mounted a NFS share,  from cli i can acces that folder and write to it,   then in mangarr i added the mounted location "/mnt/media" and i tried "/mnt/media/" after the logs i also tried "/mnt/comics/" as u showed in ur example. but same error from what i can see.


alvast bedankt voor je tijd ;P

[_mangarr.cache_logs.txt](https://github.com/tnrd-org/Mangarr/files/14947989/_mangarr.cache_logs.txt)
[_mangarr.db_logs.txt](https://github.com/tnrd-org/Mangarr/files/14947991/_mangarr.db_logs.txt)
[_mangarr.flaresolverr_logs.txt](https://github.com/tnrd-org/Mangarr/files/14947992/_mangarr.flaresolverr_logs.txt)
[_mangarr.stack_logs.txt](https://github.com/tnrd-org/Mangarr/files/14947993/_mangarr.stack_logs.txt)

**Comment by undeadalien1** [comment]
![image](https://github.com/tnrd-org/Mangarr/assets/65157246/6c47b4c1-ae73-4d81-9767-7c3e324fb624)
![image](https://github.com/tnrd-org/Mangarr/assets/65157246/641fa641-407b-4138-99d4-1d84df753acf)
![image](https://github.com/tnrd-org/Mangarr/assets/65157246/5a806313-f2f7-4dd3-a4d8-b9b3095624fc)
![image](https://github.com/tnrd-org/Mangarr/assets/65157246/fb40c84f-4841-458c-8f0b-0433df651575)

**Comment by Thundernerd** [comment]
Glad you got a bit further! Apologies that it still doesn't work properly.

From what I can see in the logs you provided it seems to fault on trying to send a notification to discord. Have you set up a discord webhook by any chance?

If so, please make sure that you're using the full URL as the value!

Geen probleem hoor!

**Comment by undeadalien1** [comment]
cheers!   
didnt comment out the discord and optional bits, done now ;)
downloaded first manga and now readable in kavita ;)

**Comment by Thundernerd** [comment]
Glad to hear that it worked!
